name: chexx_shared_models
description: Shared data models and network messages for Chexx multiplayer game
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No external dependencies - pure Dart models for maximum compatibility

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
